- name: Login Docker Hub
  uses: docker/login-action@v3
  with:
    username: ${ secrets.DOCKER_USERNAME }
    password: ${ secrets.DOCKER_PASSWORD }

- name: Build Image
  run: |
    docker build -t usuario/aula-devops:1.0.${ gitlab-run_number }

- name: Push Image
  run: |
    docker push usuario/aula-devops:1.0.${ gitlab-run_number }
